# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46543c44dc8f96051678cc96946f24b844873ff63584f62004a173a5d3003e4179e080b5515278f7dc8c0a4cc8e167d412e1ae889638c6141bb9056f1d2f5090

test:
  secret_key_base: ea509cc3acce17345b2f02c0dcf0da5f248019c8f86e4ce12a2fd3a0cf53d8e313fc3c8dbc020b989e1937fe6f71382819a9464b3857f58f69866796fcf0e42d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
